finalproject/finalproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


finalproject/myapp/urls.py
from django.urls import path

from . import views
from .views import profile,about
from .views import my_form_view

urlpatterns = [
    path('',views.index,name='index'),
    path('profile/',profile,name='profile'),
    path('about/',about,name='about'),
    path('workwithus/',my_form_view,name='my-form'),
]

finalproject/myapp/models.py
from django.db import models


class MyModel(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    wechat = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    message = models.CharField(max_length=100)

finalproject/myapp/forms.py
from django import forms
from .models import MyModel


class MyForm(forms.ModelForm):
    class Meta:
        model = MyModel
        fields = ['name', 'email', 'wechat', 'phone', 'message']

finalproject/myapp/views.py
import http.client
from django.shortcuts import render
from django.contrib import messages
from .forms import MyForm


# Create your views here.

def index(request):
    return render(request, 'index.html')


def profile(request):
    return render(request, 'profile.html')


def about(request):
    return render(request, 'about.html')


def my_form_view(request):
    if request.method == "POST":
        form = MyForm(request.POST)
        if form.is_valid():
            form.save()
        messages.success(request, 'Message submitted successfully.')
        form = MyForm()
    else:
        form = MyForm()
    return render (request,'workwithus.html',{'form':form})

finalproject/myapp/templates/about.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
{% load static %}
  <head><script src="/docs/5.3/assets/js/color-modes.js"></script>
    <title>About Us</title>

 {% include 'base.html' %}
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
      .bgimg{
      background: url({% static 'story-quinyx-happy-loyal-workforce.jpg' %}) no-repeat center center fixed;
      background-size: cover;
      }

    </style>


  </head>
  <body>

<header data-bs-theme="dark">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
  <div class="container-fluid">
   <a class="navbar-brand" href="/myapp/"><img src="{% static 'consult.png' %}" height="50"></a>
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/myapp/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' %}">Our Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'my-form' %}">Work With Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'about' %}">About Us</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>

  <div class="position-relative overflow-hidden  p-md-5  text-center bg-body-tertiary bgimg">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-4 fw-normal text-white">About Us</h1>
    </div>
  </div>
<main class="py-5 text-center">
<p class="fw-normal" >Sindibad is a search engine for the tourist through which he can search for the city or country he wants to visit or is currently visiting; it is derived from the name of the famous Arab traveler Sindibad. This search engine is to find out hotels, restaurants, entertainment venues and tour guide companies, as well as tourist can see their details. This engine can specify searching in all cities within the country or in a specific city and to see the details.
The website is done by software enginnering international students, of Nankai university:</p>
  <div class="album py-5">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'njie.jpg' %}">
            <div class="card-body">
              <p class="card-text">Isatou K. Njie</p>

              <p class="card-text"> 2120226054</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:isatoukn696@gmail.com" class=" text-reset"><i class="fas fa-envelope"></i></a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="https://www.linkedin.com/in/isatou-k-njie-b34b73185" class=" text-reset" target="_blank"> <i class="fab fa-linkedin"></i></a></button>
                </div>
              </div>
            </div>
          </div>
        </div>
       <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'nazir.jpg' %}">
            <div class="card-body">
              <p class="card-text">Ilyasu Nazir Muhammad </p>
              <p class="card-text">2120226071</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                 <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:nazirkaoje777@gmail.com" class=" text-reset"><i class="fas fa-envelope"></i></a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="https://www.linkedin.com/in/nazir-ilyasu-26238a279" class=" text-reset" target="_blank"> <i class="fab fa-linkedin"></i></a></button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'uwais.jpg' %}">
            <div class="card-body">
              <p class="card-text">Muhammad Uwais Ahmad</p>

              <p class="card-text">2120226073</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:muhduways@yahoo.com" class=" text-reset"><i class="fas fa-envelope"></i></a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:" class=" text-reset" target="_blank"> <i class="fab fa-linkedin"></i></a></button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'abba1.jpg' %}" height=>
            <div class="card-body">
              <p class="card-text">Abba Adamu Fanda</p>
              <p class="card-text">2120226076</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:Fanda1095@gmail.com" class=" text-reset"><i class="fas fa-envelope"></i></a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="https://www.linkedin.com/in/abba-fanda-7364b4121" class=" text-reset" target="_blank"> <i class="fab fa-linkedin"></i></a></button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'mayowa.jpg' %}">
            <div class="card-body">
              <p class="card-text">Adedara Olumayowa Olukolade</p>

              <p class="card-text">2120226068</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:adedaramayowa6@gmail.com" class=" text-reset"><i class="fas fa-envelope"></i></a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="https://www.linkedin.com/in/adedara-olumayowa-o-3712061b4/" class=" text-reset" target="_blank"> <i class="fab fa-linkedin"></i></a></button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</main>
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Links  -->
  <section class="py-5">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <a  href="/myapp/"><img src="{% static 'consultdark.png' %}" height="100"></a>
        </div>

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="{% url 'profile' %}" class="text-reset">Services</a>
          </p>
          <p>
            <a href="{% url 'my-form' %}" class="text-reset">Work With Us</a>
          </p>
          <p>
            <a href="{% url 'about' %}" class="text-reset">About Us</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>

        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
</main>


      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.js"
></script>


  </body>
</html>

finalproject/myapp/templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.111.3">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.css"
  rel="stylesheet"
/>
    <!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.css"
  rel="stylesheet"
/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">
  </head>
  <body>
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

finalproject/myapp/templates/messages.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-success">

      <strong>{{message}}</strong>
    </div>
 {% endfor %}
{% endif %}
{% endblock %}

finalproject/myapp/templates/workwithus.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
{% load static %}
  <head><script src="/docs/5.3/assets/js/color-modes.js"></script>
    <title>Work With Us</title>
  {% include 'base.html' %}
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
      .bgimg{
      background: url({% static 'istockphoto-1160000498-612x612.jpg' %}) no-repeat center center fixed;
      background-size: cover;
      }

    .services{
margin-top:100px;
    text-align:center;

    }
      p label{
      display:block;
      }
      p input{
      width: 300px;
      height: 5vh;
      outline:0;
  }
  #id_message{
  height:30vh;
  width:350px;
  }
    </style>


  </head>
  <body>

<header data-bs-theme="dark">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="/myapp/"><img src="{% static 'consult.png' %}" height="50"></a>
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/myapp/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' %}">Our Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'my-form' %}">Work With Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About Us</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>

 <div class="position-relative overflow-hidden  p-md-5  text-center bg-body-tertiary bgimg">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-4 fw-normal text-white">Work With Us</h1>
    </div>
  </div>

<p class="py-5 text-center">To work with us. Please fill this form below</p>
<main >
{% include 'messages.html' %}
<form method="POST" class=" text-center py-3">
  {% csrf_token %}
  {{form.as_p}}
  <input class="btn btn-outline-secondary" type="submit" value="Submit">
</form>
</main>
<footer class="text-center text-lg-start bg-light text-muted mt-4">
  <!-- Section: Links  -->
  <section class="py-3">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
         <a  href="/myapp/"><img src="{% static 'consultdark.png' %}" height="100"></a>
        </div>

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="{% url 'profile' %}" class="text-reset">Services</a>
          </p>
          <p>
            <a href="{% url 'my-form' %}" class="text-reset">Work With Us</a>
          </p>
          <p>
            <a href="{% url 'about' %}" class="text-reset">About Us</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>

        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.js"
></script>


  </body>
</html>